apiVersion: v1
kind: Service
metadata:
  name: mbition-service
  namespace: mbition
spec:
  selector:
    app: mbition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer