name: mBition deploy to EKS
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' 
      id: install
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: pip install -r requirements.txt  

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    
    - name: Run Unit Test
      run: |
        python -m unittest discover -s tests

    - name: Build, tag, and push application docker image to Docker Hub
      run: |
        IMAGE_TAG=latest
        echo $IMAGE_TAG
        docker build -t ${{secrets.DOCKER_USER}}/mbition .
        docker tag ${{secrets.DOCKER_USER}}/mbition ${{secrets.DOCKER_USER}}/mbition:$IMAGE_TAG
        docker push ${{secrets.DOCKER_USER}}/mbition:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name mbition-cluster
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml